### ISSUE TITLE
Question/suggestion: list uptime sorting from lowest to highest

### ISSUE THREAD

**Issue by mathkkad** [PedroS11/twitch-live-extension#20]
Hi!
I have been using your extension on Chrome for a while and I love it! Thank you so much for making this useful extension.
I have more of a question/idea than an issue: Since I saw you added the channel uptime counter in the extension, do you think you could implement in the future an option for sorting the list with the most recent channel uptime at the top of the list and the most channel uptime at the bottom (like uptime sorting from lowest to highest)? 
It would be really useful to see at the top of the list your most recent uptime channels, clearly seeing who just went live, and switching fast to one of the recent channels if something interesting pops up. Thank you again!

**Comment by PedroS11** [comment]
Hey!
I really appreciate your feedback, it means a lot to me as I never thought this would be used by so many people.
I never thought about that feature, I can have a look at it but, unfortunately, not in the next few months. My main goal now is to make this work on more browsers, especially Edge and then Mozilla. Making it compatible with both browsers will be a huge challenge.
But if I make the sorting available by uptime/number of viewers, you'll know it as I create a page with every new update.

**Comment by mathkkad** [comment]
It is my pleasure, I really appreciate the work you put in this extension. It is so useful that I use it daily.
Thank you for being open to my suggestion. Just take your time with the project and do the things in whatever order you feel it's necessary. I would be happy to see an uptime sorting feature in the future if you can implement that, with the most recent streams at the top, to quickly see who went live recently. I find it more useful than viewer number sorting, the way Twitch does it. 
I wish you all the best and for things to go smooth with the implementation in the Edge and Mozilla browsers. From what I know, more recent Edge versions are built in Chromium, so they may be compatible with Chrome extensions.

**Comment by PedroS11** [comment]
Yeah, I think ordering it's easy, just need to figure out the UI part of it but I'll give it a try in the future!
I think I made it work, it's a question of uploading it and guarantees that it follows the Store guidelines
