### ISSUE TITLE
Readme not complete

### ISSUE THREAD

**Issue by buryo** [PedroS11/twitch-live-extension#21]
Hi, I wanted to run the extension locally but came across problems.

I'm missing and example `config.ts` file. 
Exporting `CLIENT_ID` is not enough in my case to run the extension, it's looking for more values like: `OAUTH_BASE_URL`, `API_BASE_URL` etc.

Could you make this complete, so anyone can just clone, follow installation and setup steps and have a running application?

**Comment by PedroS11** [comment]
Hey,
Next week, I think I'll make a new release of the extension and I'll take this into consideration and update the readme.
Just to help you now until I make the change, here is what's missing from the file:


export const RESPONSE_TYPE_TOKEN = 'token';
export const SCOPES: string[] = ['user:read:follows'];
export const OAUTH_BASE_URL = 'https://id.twitch.tv/oauth2';
export const API_BASE_URL = 'https://api.twitch.tv/helix';

**Comment by buryo** [comment]
Thanks!

Question: You are using Redux-toolkit. 
Something I really want to use in my personal Chrome extension.
The problem so far I have: 
`Background.js` is running in another context than `Content.js` and `Popup.js`. How do you keep the state persistent in your project?

Maybe in your case you just need the state available in Background.js and not Popup.js.
