### ISSUE TITLE
White edges / color issue

### ISSUE THREAD

**Issue by Osahashi** [PedroS11/twitch-live-extension#23]
I am using LibreWolf 99.0.1-4 and see that something is wrong with the color. There are these white spots visible to me at the edge, what could be the reason for that?

<img width="254" alt="Screenshot 2022-05-03 134358" src="https://user-images.githubusercontent.com/22057956/166447561-466e5c76-5ceb-42c1-bfdf-77d0338f0fa6.png">

<img width="246" alt="Screenshot 2022-05-03 134523" src="https://user-images.githubusercontent.com/22057956/166447572-7e70888c-05c9-4430-9077-d63cd50d1616.png">

**Comment by PedroS11** [comment]
Hey, thank you for the heads up!
It seems that all Firefox based browsers are having this issue. In the next few days, I'll try to debug it and fix it, it might be some specific classname that I missing.

**Comment by PedroS11** [comment]
Quick update, I found no solution for it, it seems we are not the only ones with the issue as it's Firefox related. For some reason, Firefox adds a white round border on the popup and I can't remove it and make it clean. I'll continue to search for a solution for it, sorry.
https://www.reddit.com/r/FirefoxCSS/comments/uhoyns/is_it_possible_to_remove_the_default_white_border/
