### ISSUE TITLE
Extension asking for re-authentication and still can't see the list

### ISSUE THREAD

**Issue by ProjectXsent** [PedroS11/twitch-live-extension#40]
It seems to happen when there are more than 100+ channels that I follow went live.

I use the extension on the Opera GX browser since the built-in extension wasn't working that time and in your extension, I can see how long is their stream which I prefer more than the built-in.

**Comment by PedroS11** [comment]
I'll try to have a look at it on the weekend, because the number of follows shouldn't have any relation to the authentication

**Comment by PedroS11** [comment]
With this new update, this shouldn't happen again. Feel free to create a new issue if you get this error again.
