### ISSUE TITLE
Suggestion let the user select which streamers receive a notification.

### ISSUE THREAD

**Issue by this-is-jewl** [PedroS11/twitch-live-extension#50]
It would be nice to select only the streamers you want to be notified, unlike how it is right now, that you receive a notification on everyone you follow

**Comment by PedroS11** [comment]
Unfortunately, if I was to add that functionality, I'd need a server to store the notifications options for each user and that is impossible right now for me. Having it stored in the local storage, wouldn't be a good solution to be honest
